### ISSUE TITLE
Condition expression returns non-Boolean:  Result has class java.lang.String and not java.lang.Boolean

### ISSUE THREAD

**Issue by CNFRaspberry** [camunda/camunda-external-task-client-js#21]
I am receiving the following error "Condition expression returns non-Boolean:  Result has class java.lang.String and not java.lang.Boolean" when I'm trying to run the following script;

const { Client, logger } = require("camunda-external-task-client-js");
const { Variables } = require("camunda-external-task-client-js");

// configuration for the Client:
//  - 'baseUrl': url to the Workflow Engine
//  - 'logger': utility to automatically log important events
const config = { baseUrl: "http://localhost:8080/engine-rest", use: logger };

// create a Client instance with custom configuration
const client = new Client(config);

// susbscribe to the topic: 'creditScoreChecker'
client.subscribe("DecideOnExpansion", async function({ task, taskService }) {
  // Put your business logic
	
	var north = Math.random() >= 0.5;	
	const variables = new Variables();
	variables.set("north", north);	
	var north_val = variables.get("north");	

  // complete the task
  await taskService.complete(task, variables);
});

Would someone point me in the right direction?

![Camunda Error](https://user-images.githubusercontent.com/52674821/60834468-fc74ae80-a17d-11e9-8c62-45ef790ee83a.PNG)

**Comment by benhoffmann** [comment]
Hi @CNFRaspberry , 

your problem is most likely caused by a gateway further down in the process. I assume that you are using () instead of {} for the expressions. Since you don't have an asnyc after in place for the external service task, the call to complete will try to synchronously execute the rest of the  workflow. You hit the problem at the gateway, roll back and see the response in your external task worker. For more info, have a look here: https://docs.camunda.org/manual/7.11/user-guide/process-engine/transactions-in-processes/

**Comment by CNFRaspberry** [comment]
Hello Ben,

Thanks for your help!  You are correct, updated the expressions in the Camunda model to Curly Braces and everything worked.

#(not north) -> #{not north}
and
#(north) -> #{north}

Thanks again!

Regards,
Kevin
